[package]
name = "colorimetry"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.33"
approx = "0.5"
wasm-bindgen = "0.2"
once_cell = "1.0"
url = "2.5.2"
libm = "0.2.8"

[lib]
crate-type = ["cdylib", "rlib"]
